package:
  name: plume
  version: 0.1

source:
  git_url: https://github.com/mcflugen/plume

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cythongsl
    - landlab

  run:
    - python
    - setuptools
    - numpy
    - landlab

test:
  imports:
    - plume

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

about:
  home: https://github.com/mcflugen/plume
  license: MIT
  license_file: LICENSE
  summary: A hypopycnal sediment-carrying plume entering the ocean
  dev_url: https://github.com/mcflugen/plume
